// ============================================================
//  activity-data.js  —  运营商活动数据配置（80条数据，移动36条）
//  修改此文件即可增删改活动，无需改动 HTML
// ============================================================

// 主大类定义（页面 Tab 和下拉会读取）
const mainTypeEnum = [
    { value: "", label: "全部大类" },
    { value: "流量类", label: "流量类" },
    { value: "话费充值类", label: "话费充值类" },
    { value: "会员权益类", label: "会员权益类" },
    { value: "号卡套餐类", label: "号卡套餐类" },
    { value: "宽带业务", label: "宽带业务" },
    { value: "合约购机", label: "合约购机" },
    { value: "其他活动", label: "其他活动" }
];

// 细分标签库（主大类 → 细分标签列表，用于下拉联动）
const subTypeMap = {
    "流量类": ["全国通用流量", "定向流量", "闲时流量", "流量叠加包", "赠送流量"],
    "话费充值类": ["充值立减", "充送话费", "话费返还", "缴费优惠"],
    "会员权益类": ["视频会员", "音乐会员", "网盘会员", "出行券", "生活权益"],
    "号卡套餐类": ["新用户号卡", "老用户套餐", "副卡", "亲情号"],
    "宽带业务": ["新装宽带", "宽带提速", "宽带续费", "IPTV"],
    "合约购机": ["合约机", "购机补贴", "以旧换新"],
    "其他活动": ["抽奖活动", "签到", "老用户专享", "新用户专享"]
};

// ============================================================
//  ★★★ 活动数据列表（80条，移动36条） ★★★
// ============================================================
const activityList = [
    // ===== 移动 36条 =====
    {
        id: 1,
        operator: "移动",
        province: "全国",
        city: "全国",
        mainType: "流量类",
        subType: ["全国通用流量", "赠送流量"],
        title: "移动全国通用流量包买一送一",
        startTime: "2026-08-01",
        endTime: "2026-09-30",
        desc: "购买30G全国通用流量包，赠送30G同等流量",
        link: "https://www.10086.cn",
        remark: "限时特惠，每人限购1次"
    },
    {
        id: 2,
        operator: "移动",
        province: "广东省",
        city: "广州市",
        mainType: "话费充值类",
        subType: ["充值立减"],
        title: "广州移动充值满100立减20",
        startTime: "2026-08-01",
        endTime: "2026-08-31",
        desc: "通过移动APP充值100元话费，立减20元优惠",
        link: "",
        remark: "仅限广州移动用户"
    },
    {
        id: 3,
        operator: "移动",
        province: "北京市",
        city: "北京市",
        mainType: "会员权益类",
        subType: ["视频会员"],
        title: "北京移动用户免费领爱奇艺月卡",
        startTime: "2026-08-10",
        endTime: "2026-09-10",
        desc: "北京移动用户可免费领取爱奇艺黄金会员月卡",
        link: "",
        remark: "限量5000份"
    },
    {
        id: 4,
        operator: "移动",
        province: "浙江省",
        city: "杭州市",
        mainType: "号卡套餐类",
        subType: ["新用户号卡", "赠送流量"],
        title: "杭州移动新用户19元享80G流量",
        startTime: "2026-08-01",
        endTime: "2026-10-31",
        desc: "新办理用户首月19元享80G全国通用流量",
        link: "https://zj.10086.cn",
        remark: "限18-30岁用户"
    },
    {
        id: 5,
        operator: "移动",
        province: "江苏省",
        city: "南京市",
        mainType: "宽带业务",
        subType: ["新装宽带", "IPTV"],
        title: "南京移动新装宽带送IPTV+路由器",
        startTime: "2026-08-01",
        endTime: "2026-09-30",
        desc: "新装300M宽带，赠送IPTV和WiFi6路由器",
        link: "",
        remark: "合约期24个月"
    },
    {
        id: 6,
        operator: "移动",
        province: "四川省",
        city: "成都市",
        mainType: "合约购机",
        subType: ["合约机"],
        title: "成都移动华为Mate70合约机直降1000",
        startTime: "2026-08-10",
        endTime: "2026-09-30",
        desc: "办理139元及以上套餐，Mate70直降1000元",
        link: "",
        remark: "限指定营业厅"
    },
    {
        id: 7,
        operator: "移动",
        province: "湖北省",
        city: "武汉市",
        mainType: "其他活动",
        subType: ["抽奖活动"],
        title: "武汉移动用户抽奖赢iPhone16",
        startTime: "2026-08-15",
        endTime: "2026-08-31",
        desc: "每日登录移动APP可参与抽奖，奖品含iPhone16",
        link: "",
        remark: "每人每日1次抽奖机会"
    },
    {
        id: 8,
        operator: "移动",
        province: "全国",
        city: "全国",
        mainType: "流量类",
        subType: ["闲时流量"],
        title: "移动夜间流量包5元享30G",
        startTime: "2026-08-01",
        endTime: "2026-12-31",
        desc: "夜间23:00-次日7:00流量30G仅需5元/月",
        link: "https://www.10086.cn",
        remark: "自动续订，随时退订"
    },
    {
        id: 9,
        operator: "移动",
        province: "山东省",
        city: "济南市",
        mainType: "话费充值类",
        subType: ["充送话费"],
        title: "济南移动充200送50话费券",
        startTime: "2026-08-01",
        endTime: "2026-08-31",
        desc: "一次性充值200元，赠送50元话费券",
        link: "",
        remark: "仅限济南移动用户"
    },
    {
        id: 10,
        operator: "移动",
        province: "福建省",
        city: "厦门市",
        mainType: "会员权益类",
        subType: ["生活权益"],
        title: "厦门移动用户领20元外卖券",
        startTime: "2026-08-10",
        endTime: "2026-08-31",
        desc: "厦门移动用户可领取美团/饿了么20元红包",
        link: "",
        remark: "限量每日100份"
    },
    {
        id: 11,
        operator: "移动",
        province: "广东省",
        city: "深圳市",
        mainType: "宽带业务",
        subType: ["宽带提速"],
        title: "深圳移动免费提速至1000M",
        startTime: "2026-08-01",
        endTime: "2026-08-31",
        desc: "现有500M用户可免费提速至1000M光纤",
        link: "",
        remark: "需签约12个月"
    },
    {
        id: 12,
        operator: "移动",
        province: "上海市",
        city: "上海市",
        mainType: "号卡套餐类",
        subType: ["老用户套餐"],
        title: "上海移动老用户加装副卡免月租一年",
        startTime: "2026-08-01",
        endTime: "2026-09-30",
        desc: "主卡58元及以上套餐用户，副卡免12个月月租",
        link: "",
        remark: "限1张副卡"
    },
    {
        id: 13,
        operator: "移动",
        province: "河南省",
        city: "郑州市",
        mainType: "流量类",
        subType: ["定向流量", "流量叠加包"],
        title: "郑州移动抖音/快手定向流量包",
        startTime: "2026-08-01",
        endTime: "2026-10-31",
        desc: "15元享30GB抖音+快手定向流量，赠送5GB通用",
        link: "",
        remark: "自动续订"
    },
    {
        id: 14,
        operator: "移动",
        province: "浙江省",
        city: "杭州市",
        mainType: "合约购机",
        subType: ["购机补贴"],
        title: "杭州移动购机补贴最高1200元",
        startTime: "2026-08-10",
        endTime: "2026-09-30",
        desc: "办理指定5G套餐购机享补贴，最高1200元",
        link: "https://zj.10086.cn",
        remark: "限指定机型"
    },
    {
        id: 15,
        operator: "移动",
        province: "全国",
        city: "全国",
        mainType: "其他活动",
        subType: ["签到"],
        title: "移动用户签到领流量",
        startTime: "2026-08-01",
        endTime: "2026-12-31",
        desc: "每日签到可领取50-200MB流量，连续签到7天送1GB",
        link: "",
        remark: "长期有效"
    },
    {
        id: 16,
        operator: "移动",
        province: "江苏省",
        city: "苏州市",
        mainType: "话费充值类",
        subType: ["缴费优惠"],
        title: "苏州移动缴话费送5GB流量",
        startTime: "2026-08-15",
        endTime: "2026-09-15",
        desc: "通过移动APP缴话费满50元送5GB流量包",
        link: "",
        remark: "每月限1次"
    },
    {
        id: 17,
        operator: "移动",
        province: "四川省",
        city: "成都市",
        mainType: "会员权益类",
        subType: ["音乐会员"],
        title: "成都移动免费领QQ音乐月卡",
        startTime: "2026-08-10",
        endTime: "2026-09-10",
        desc: "成都移动用户可免费领取QQ音乐豪华绿钻月卡",
        link: "",
        remark: "限成都号码"
    },
    {
        id: 18,
        operator: "移动",
        province: "山东省",
        city: "青岛市",
        mainType: "宽带业务",
        subType: ["宽带续费"],
        title: "青岛移动宽带续费送智能音箱",
        startTime: "2026-08-01",
        endTime: "2026-09-30",
        desc: "续费500M宽带一年，赠送智能音箱一台",
        link: "",
        remark: "需一次性续费"
    },
    {
        id: 19,
        operator: "移动",
        province: "北京市",
        city: "北京市",
        mainType: "号卡套餐类",
        subType: ["亲情号"],
        title: "北京移动亲情号免费互拨",
        startTime: "2026-08-01",
        endTime: "2026-10-31",
        desc: "最多绑定4个亲情号，全国互拨免费",
        link: "",
        remark: "仅限北京移动用户"
    },
    {
        id: 20,
        operator: "移动",
        province: "全国",
        city: "全国",
        mainType: "流量类",
        subType: ["全国通用流量"],
        title: "移动20元10GB通用流量特惠",
        startTime: "2026-08-01",
        endTime: "2026-08-20",
        desc: "20元购10GB全国通用流量，有效期7天",
        link: "https://www.10086.cn",
        remark: "即将到期"
    },
    {
        id: 21,
        operator: "移动",
        province: "广东省",
        city: "广州市",
        mainType: "合约购机",
        subType: ["以旧换新"],
        title: "广州移动以旧换新补贴2000元",
        startTime: "2026-08-01",
        endTime: "2026-09-30",
        desc: "旧机回收换新机，最高补贴2000元",
        link: "",
        remark: "需评估旧机价值"
    },
    {
        id: 22,
        operator: "移动",
        province: "湖北省",
        city: "武汉市",
        mainType: "其他活动",
        subType: ["老用户专享"],
        title: "武汉移动老用户免费领10G流量",
        startTime: "2026-08-01",
        endTime: "2026-08-31",
        desc: "在网满2年用户可免费领取10GB通用流量",
        link: "",
        remark: "发送短信到10086领取"
    },
    {
        id: 23,
        operator: "移动",
        province: "上海市",
        city: "上海市",
        mainType: "话费充值类",
        subType: ["话费返还"],
        title: "上海移动话费返还活动",
        startTime: "2026-08-15",
        endTime: "2026-09-15",
        desc: "充值500元返还150元话费，分3个月返还",
        link: "",
        remark: "需承诺在网12个月"
    },
    {
        id: 24,
        operator: "移动",
        province: "江苏省",
        city: "南京市",
        mainType: "会员权益类",
        subType: ["出行券"],
        title: "南京移动用户领滴滴20元券",
        startTime: "2026-08-10",
        endTime: "2026-08-31",
        desc: "南京移动用户可领取滴滴20元打车券",
        link: "",
        remark: "限量1000份"
    },
    {
        id: 25,
        operator: "移动",
        province: "福建省",
        city: "福州市",
        mainType: "宽带业务",
        subType: ["新装宽带"],
        title: "福州移动新装宽带首月免费",
        startTime: "2026-08-01",
        endTime: "2026-09-30",
        desc: "新装200M宽带，首月0元体验",
        link: "",
        remark: "合约期12个月"
    },
    {
        id: 26,
        operator: "移动",
        province: "四川省",
        city: "绵阳市",
        mainType: "流量类",
        subType: ["赠送流量"],
        title: "绵阳移动用户生日月送20G流量",
        startTime: "2026-08-01",
        endTime: "2026-12-31",
        desc: "生日当月可免费领取20GB全国通用流量",
        link: "",
        remark: "需实名认证"
    },
    {
        id: 27,
        operator: "移动",
        province: "河南省",
        city: "洛阳市",
        mainType: "号卡套餐类",
        subType: ["新用户号卡"],
        title: "洛阳移动29元80G大流量卡",
        startTime: "2026-08-01",
        endTime: "2026-10-31",
        desc: "新用户29元/月享80G流量+200分钟通话",
        link: "",
        remark: "限18-28岁用户"
    },
    {
        id: 28,
        operator: "移动",
        province: "全国",
        city: "全国",
        mainType: "其他活动",
        subType: ["新用户专享"],
        title: "移动新用户首充50送50话费",
        startTime: "2026-08-01",
        endTime: "2026-09-30",
        desc: "新开卡用户首次充值50元赠送50元话费",
        link: "",
        remark: "分5个月返还"
    },
    {
        id: 29,
        operator: "移动",
        province: "浙江省",
        city: "宁波市",
        mainType: "合约购机",
        subType: ["合约机"],
        title: "宁波移动小米14合约机直降800",
        startTime: "2026-08-10",
        endTime: "2026-09-10",
        desc: "办理99元套餐，小米14直降800元",
        link: "",
        remark: "限量50台"
    },
    {
        id: 30,
        operator: "移动",
        province: "山东省",
        city: "烟台市",
        mainType: "话费充值类",
        subType: ["充值立减"],
        title: "烟台移动充50减5元优惠",
        startTime: "2026-08-15",
        endTime: "2026-08-31",
        desc: "通过移动APP充值50元立减5元，限移动用户",
        link: "",
        remark: "每人限1次"
    },
    {
        id: 31,
        operator: "移动",
        province: "广东省",
        city: "东莞市",
        mainType: "会员权益类",
        subType: ["网盘会员"],
        title: "东莞移动免费领天翼云盘会员",
        startTime: "2026-08-01",
        endTime: "2026-09-30",
        desc: "东莞移动用户可免费领取3个月天翼云盘会员",
        link: "",
        remark: "限东莞号码"
    },
    {
        id: 32,
        operator: "移动",
        province: "北京市",
        city: "北京市",
        mainType: "流量类",
        subType: ["定向流量"],
        title: "北京移动爱奇艺定向免流包",
        startTime: "2026-08-01",
        endTime: "2026-12-31",
        desc: "10元/月享爱奇艺30GB定向流量",
        link: "https://bj.10086.cn",
        remark: "自动续订"
    },
    {
        id: 33,
        operator: "移动",
        province: "江苏省",
        city: "无锡市",
        mainType: "宽带业务",
        subType: ["宽带提速"],
        title: "无锡移动免费提速至300M",
        startTime: "2026-08-01",
        endTime: "2026-09-30",
        desc: "现有100M用户可免费提速至300M",
        link: "",
        remark: "需在网满6个月"
    },
    {
        id: 34,
        operator: "移动",
        province: "四川省",
        city: "成都市",
        mainType: "号卡套餐类",
        subType: ["副卡"],
        title: "成都移动副卡月租优惠",
        startTime: "2026-08-01",
        endTime: "2026-10-31",
        desc: "主号79元及以上套餐，副卡仅需5元/月",
        link: "",
        remark: "限3张副卡"
    },
    {
        id: 35,
        operator: "移动",
        province: "湖北省",
        city: "武汉市",
        mainType: "其他活动",
        subType: ["签到"],
        title: "武汉移动签到积分享好礼",
        startTime: "2026-08-01",
        endTime: "2026-12-31",
        desc: "每日签到可积累积分，可兑换话费流量",
        link: "",
        remark: "积分有效期1年"
    },
    {
        id: 36,
        operator: "移动",
        province: "全国",
        city: "全国",
        mainType: "话费充值类",
        subType: ["充送话费"],
        title: "移动全国话费充100送30",
        startTime: "2026-08-20",
        endTime: "2026-09-20",
        desc: "通过移动官方渠道充值100元，额外赠送30元话费",
        link: "https://www.10086.cn",
        remark: "限移动用户"
    },

    // ===== 联通 14条 =====
    {
        id: 37,
        operator: "联通",
        province: "全国",
        city: "全国",
        mainType: "流量类",
        subType: ["全国通用流量", "赠送流量"],
        title: "联通全国通用流量包限时8折",
        startTime: "2026-08-01",
        endTime: "2026-09-15",
        desc: "所有流量包8折优惠，最高可省60元",
        link: "https://www.10010.com",
        remark: "限时特惠"
    },
    {
        id: 38,
        operator: "联通",
        province: "广东省",
        city: "广州市",
        mainType: "话费充值类",
        subType: ["充值立减"],
        title: "广州联通充值满200立减30",
        startTime: "2026-08-01",
        endTime: "2026-08-31",
        desc: "通过联通APP充值200元立减30元",
        link: "",
        remark: "仅限广州联通"
    },
    {
        id: 39,
        operator: "联通",
        province: "北京市",
        city: "北京市",
        mainType: "会员权益类",
        subType: ["视频会员"],
        title: "北京联通免费领优酷会员月卡",
        startTime: "2026-08-10",
        endTime: "2026-09-10",
        desc: "北京联通用户可免费领取优酷VIP月卡",
        link: "",
        remark: "限量2000份"
    },
    {
        id: 40,
        operator: "联通",
        province: "浙江省",
        city: "杭州市",
        mainType: "号卡套餐类",
        subType: ["新用户号卡"],
        title: "杭州联通新用户29元60G套餐",
        startTime: "2026-08-01",
        endTime: "2026-10-31",
        desc: "新用户29元/月享60G全国流量+100分钟通话",
        link: "https://zj.10010.com",
        remark: "限25岁以下用户"
    },
    {
        id: 41,
        operator: "联通",
        province: "上海市",
        city: "上海市",
        mainType: "宽带业务",
        subType: ["新装宽带"],
        title: "上海联通新装500M宽带送WiFi6路由",
        startTime: "2026-08-01",
        endTime: "2026-09-30",
        desc: "新装500M宽带，赠送WiFi6路由器一台",
        link: "",
        remark: "合约期24个月"
    },
    {
        id: 42,
        operator: "联通",
        province: "江苏省",
        city: "南京市",
        mainType: "合约购机",
        subType: ["合约机"],
        title: "南京联通OPPO Find X8合约机优惠",
        startTime: "2026-08-10",
        endTime: "2026-09-30",
        desc: "办理129元套餐，Find X8直降1200元",
        link: "",
        remark: "限指定营业厅"
    },
    {
        id: 43,
        operator: "联通",
        province: "四川省",
        city: "成都市",
        mainType: "其他活动",
        subType: ["抽奖活动"],
        title: "成都联通用户抽奖赢全年话费",
        startTime: "2026-08-15",
        endTime: "2026-08-31",
        desc: "登录联通APP即可参与抽奖，最高赢全年话费",
        link: "",
        remark: "每人每日1次"
    },
    {
        id: 44,
        operator: "联通",
        province: "全国",
        city: "全国",
        mainType: "流量类",
        subType: ["定向流量"],
        title: "联通B站定向免流包",
        startTime: "2026-08-01",
        endTime: "2026-12-31",
        desc: "10元/月享B站30GB定向流量",
        link: "https://www.10010.com",
        remark: "自动续订"
    },
    {
        id: 45,
        operator: "联通",
        province: "山东省",
        city: "济南市",
        mainType: "话费充值类",
        subType: ["充送话费"],
        title: "济南联通充300送100话费",
        startTime: "2026-08-01",
        endTime: "2026-08-31",
        desc: "一次性充值300元赠送100元话费券",
        link: "",
        remark: "分3个月返还"
    },
    {
        id: 46,
        operator: "联通",
        province: "湖北省",
        city: "武汉市",
        mainType: "会员权益类",
        subType: ["音乐会员"],
        title: "武汉联通免费领网易云会员",
        startTime: "2026-08-10",
        endTime: "2026-09-10",
        desc: "武汉联通用户可免费领取网易云音乐月卡",
        link: "",
        remark: "限武汉号码"
    },
    {
        id: 47,
        operator: "联通",
        province: "广东省",
        city: "深圳市",
        mainType: "宽带业务",
        subType: ["宽带续费"],
        title: "深圳联通宽带续费送100元话费",
        startTime: "2026-08-01",
        endTime: "2026-09-30",
        desc: "续费宽带一年赠送100元话费",
        link: "",
        remark: "需一次性续费"
    },
    {
        id: 48,
        operator: "联通",
        province: "福建省",
        city: "厦门市",
        mainType: "号卡套餐类",
        subType: ["老用户套餐"],
        title: "厦门联通老用户免费升级套餐",
        startTime: "2026-08-01",
        endTime: "2026-10-31",
        desc: "在网满1年老用户可免费升级至更高档次套餐",
        link: "",
        remark: "需到厅办理"
    },
    {
        id: 49,
        operator: "联通",
        province: "河南省",
        city: "郑州市",
        mainType: "流量类",
        subType: ["闲时流量"],
        title: "郑州联通夜间流量包特价",
        startTime: "2026-08-01",
        endTime: "2026-09-30",
        desc: "夜间流量50G仅需8元/月",
        link: "",
        remark: "自动续订"
    },
    {
        id: 50,
        operator: "联通",
        province: "全国",
        city: "全国",
        mainType: "合约购机",
        subType: ["购机补贴"],
        title: "联通全国购机补贴最高1500元",
        startTime: "2026-08-10",
        endTime: "2026-09-30",
        desc: "办理5G融合套餐购机补贴最高1500元",
        link: "https://www.10010.com",
        remark: "限指定机型"
    },

    // ===== 电信 15条 =====
    {
        id: 51,
        operator: "电信",
        province: "全国",
        city: "全国",
        mainType: "流量类",
        subType: ["全国通用流量"],
        title: "电信全国通用流量日包特惠",
        startTime: "2026-08-01",
        endTime: "2026-08-31",
        desc: "10GB全国通用流量日包仅需3元",
        link: "https://www.189.cn",
        remark: "每日限购1次"
    },
    {
        id: 52,
        operator: "电信",
        province: "广东省",
        city: "广州市",
        mainType: "话费充值类",
        subType: ["缴费优惠"],
        title: "广州电信缴费满100送10GB流量",
        startTime: "2026-08-01",
        endTime: "2026-08-31",
        desc: "通过电信APP缴费满100元送10GB流量",
        link: "",
        remark: "仅限广州电信"
    },
    {
        id: 53,
        operator: "电信",
        province: "上海市",
        city: "上海市",
        mainType: "会员权益类",
        subType: ["生活权益", "出行券"],
        title: "上海电信用户领30元生活礼包",
        startTime: "2026-08-10",
        endTime: "2026-09-10",
        desc: "上海电信用户可领取30元生活券（外卖/出行）",
        link: "",
        remark: "限量3000份"
    },
    {
        id: 54,
        operator: "电信",
        province: "浙江省",
        city: "杭州市",
        mainType: "号卡套餐类",
        subType: ["新用户号卡"],
        title: "杭州电信19元50G青年卡",
        startTime: "2026-08-01",
        endTime: "2026-10-31",
        desc: "新用户19元/月享50G流量+100分钟通话",
        link: "https://zj.189.cn",
        remark: "限22岁以下用户"
    },
    {
        id: 55,
        operator: "电信",
        province: "江苏省",
        city: "南京市",
        mainType: "宽带业务",
        subType: ["新装宽带", "IPTV"],
        title: "南京电信新装千兆宽带送IPTV年包",
        startTime: "2026-08-01",
        endTime: "2026-09-30",
        desc: "新装1000M宽带，赠送IPTV年包",
        link: "",
        remark: "合约期24个月"
    },
    {
        id: 56,
        operator: "电信",
        province: "四川省",
        city: "成都市",
        mainType: "合约购机",
        subType: ["以旧换新"],
        title: "成都电信以旧换新补贴1800元",
        startTime: "2026-08-10",
        endTime: "2026-09-30",
        desc: "旧机回收换新机，最高补贴1800元",
        link: "",
        remark: "需评估旧机"
    },
    {
        id: 57,
        operator: "电信",
        province: "湖北省",
        city: "武汉市",
        mainType: "其他活动",
        subType: ["签到"],
        title: "武汉电信签到领流量和话费",
        startTime: "2026-08-01",
        endTime: "2026-12-31",
        desc: "每日签到可获得流量，连续签到得话费",
        link: "",
        remark: "长期有效"
    },
    {
        id: 58,
        operator: "电信",
        province: "全国",
        city: "全国",
        mainType: "流量类",
        subType: ["定向流量"],
        title: "电信腾讯系定向免流包",
        startTime: "2026-08-01",
        endTime: "2026-12-31",
        desc: "10元/月享腾讯视频+微信30GB定向流量",
        link: "",
        remark: "自动续订"
    },
    {
        id: 59,
        operator: "电信",
        province: "山东省",
        city: "济南市",
        mainType: "话费充值类",
        subType: ["话费返还"],
        title: "济南电信充500返150话费",
        startTime: "2026-08-15",
        endTime: "2026-09-15",
        desc: "充值500元返还150元话费，分6个月返还",
        link: "",
        remark: "需承诺在网12个月"
    },
    {
        id: 60,
        operator: "电信",
        province: "福建省",
        city: "厦门市",
        mainType: "会员权益类",
        subType: ["视频会员"],
        title: "厦门电信免费领芒果TV月卡",
        startTime: "2026-08-10",
        endTime: "2026-09-10",
        desc: "厦门电信用户可免费领取芒果TV月卡",
        link: "",
        remark: "限厦门号码"
    },
    {
        id: 61,
        operator: "电信",
        province: "广东省",
        city: "深圳市",
        mainType: "宽带业务",
        subType: ["宽带提速"],
        title: "深圳电信免费提速至500M",
        startTime: "2026-08-01",
        endTime: "2026-08-31",
        desc: "现有200M用户免费提速至500M",
        link: "",
        remark: "需在网满12个月"
    },
    {
        id: 62,
        operator: "电信",
        province: "北京市",
        city: "北京市",
        mainType: "号卡套餐类",
        subType: ["副卡"],
        title: "北京电信副卡免费共享流量",
        startTime: "2026-08-01",
        endTime: "2026-10-31",
        desc: "主卡99元及以上套餐，副卡免月租共享流量",
        link: "",
        remark: "限2张副卡"
    },
    {
        id: 63,
        operator: "电信",
        province: "河南省",
        city: "郑州市",
        mainType: "流量类",
        subType: ["流量叠加包"],
        title: "郑州电信流量叠加包买二送一",
        startTime: "2026-08-01",
        endTime: "2026-08-31",
        desc: "购买2个月流量包赠送1个月同等流量",
        link: "",
        remark: "限指定流量包"
    },
    {
        id: 64,
        operator: "电信",
        province: "浙江省",
        city: "宁波市",
        mainType: "合约购机",
        subType: ["购机补贴"],
        title: "宁波电信购机补贴最高1000元",
        startTime: "2026-08-10",
        endTime: "2026-09-30",
        desc: "办理129元套餐购机补贴最高1000元",
        link: "",
        remark: "限指定机型"
    },
    {
        id: 65,
        operator: "电信",
        province: "全国",
        city: "全国",
        mainType: "其他活动",
        subType: ["新用户专享"],
        title: "电信新用户首月免月租",
        startTime: "2026-08-01",
        endTime: "2026-09-30",
        desc: "新开卡用户首月月租全免",
        link: "https://www.189.cn",
        remark: "仅限新用户"
    },

    // ===== 广电 15条 =====
    {
        id: 66,
        operator: "广电",
        province: "全国",
        city: "全国",
        mainType: "流量类",
        subType: ["赠送流量"],
        title: "广电用户每月免费领5G流量",
        startTime: "2026-08-01",
        endTime: "2026-10-31",
        desc: "广电用户每月可免费领取5GB通用流量",
        link: "https://www.10099.com.cn",
        remark: "需手动领取"
    },
    {
        id: 67,
        operator: "广电",
        province: "广东省",
        city: "广州市",
        mainType: "话费充值类",
        subType: ["充值立减"],
        title: "广州广电充值满50立减10元",
        startTime: "2026-08-01",
        endTime: "2026-08-31",
        desc: "通过广电APP充值50元立减10元",
        link: "",
        remark: "仅限广州广电"
    },
    {
        id: 68,
        operator: "广电",
        province: "北京市",
        city: "北京市",
        mainType: "会员权益类",
        subType: ["视频会员"],
        title: "北京广电用户免费领哔哩哔哩月卡",
        startTime: "2026-08-10",
        endTime: "2026-09-10",
        desc: "北京广电用户可领取B站大会员月卡",
        link: "",
        remark: "限量1000份"
    },
    {
        id: 69,
        operator: "广电",
        province: "全国",
        city: "全国",
        mainType: "号卡套餐类",
        subType: ["新用户号卡"],
        title: "广电5G青春卡19元60G",
        startTime: "2026-08-01",
        endTime: "2026-12-31",
        desc: "新用户19元/月享60G全国流量",
        link: "https://www.10099.com.cn",
        remark: "限25岁以下"
    },
    {
        id: 70,
        operator: "广电",
        province: "浙江省",
        city: "杭州市",
        mainType: "宽带业务",
        subType: ["新装宽带"],
        title: "杭州广电新装宽带送4K机顶盒",
        startTime: "2026-08-01",
        endTime: "2026-09-30",
        desc: "新装300M宽带赠送4K智能机顶盒",
        link: "",
        remark: "合约期12个月"
    },
    {
        id: 71,
        operator: "广电",
        province: "江苏省",
        city: "南京市",
        mainType: "合约购机",
        subType: ["合约机"],
        title: "南京广电vivo合约机优惠",
        startTime: "2026-08-10",
        endTime: "2026-09-30",
        desc: "办理99元套餐，vivo手机直降800元",
        link: "",
        remark: "限指定机型"
    },
    {
        id: 72,
        operator: "广电",
        province: "四川省",
        city: "成都市",
        mainType: "其他活动",
        subType: ["签到"],
        title: "成都广电签到赢流量话费",
        startTime: "2026-08-01",
        endTime: "2026-12-31",
        desc: "每日签到可累计积分兑换流量和话费",
        link: "",
        remark: "长期有效"
    },
    {
        id: 73,
        operator: "广电",
        province: "全国",
        city: "全国",
        mainType: "流量类",
        subType: ["全国通用流量"],
        title: "广电全国流量包限时7折",
        startTime: "2026-08-01",
        endTime: "2026-08-31",
        desc: "所有全国流量包7折优惠，最高省40元",
        link: "https://www.10099.com.cn",
        remark: "限时特惠"
    },
    {
        id: 74,
        operator: "广电",
        province: "湖北省",
        city: "武汉市",
        mainType: "话费充值类",
        subType: ["充送话费"],
        title: "武汉广电充200送50话费",
        startTime: "2026-08-01",
        endTime: "2026-08-31",
        desc: "充值200元赠送50元话费",
        link: "",
        remark: "仅限武汉广电"
    },
    {
        id: 75,
        operator: "广电",
        province: "上海市",
        city: "上海市",
        mainType: "会员权益类",
        subType: ["出行券"],
        title: "上海广电用户领打车券包",
        startTime: "2026-08-10",
        endTime: "2026-09-10",
        desc: "上海广电用户可领取价值30元打车券包",
        link: "",
        remark: "限量2000份"
    },
    {
        id: 76,
        operator: "广电",
        province: "山东省",
        city: "济南市",
        mainType: "宽带业务",
        subType: ["宽带续费"],
        title: "济南广电宽带续费送两个月",
        startTime: "2026-08-01",
        endTime: "2026-09-30",
        desc: "续费一年赠送两个月宽带时长",
        link: "",
        remark: "需一次性续费"
    },
    {
        id: 77,
        operator: "广电",
        province: "福建省",
        city: "厦门市",
        mainType: "号卡套餐类",
        subType: ["老用户套餐"],
        title: "厦门广电老用户套餐升级优惠",
        startTime: "2026-08-01",
        endTime: "2026-10-31",
        desc: "在网满6个月老用户可享套餐升级优惠",
        link: "",
        remark: "限厦门号码"
    },
    {
        id: 78,
        operator: "广电",
        province: "河南省",
        city: "郑州市",
        mainType: "流量类",
        subType: ["赠送流量"],
        title: "郑州广电用户生日送10G流量",
        startTime: "2026-08-01",
        endTime: "2026-12-31",
        desc: "生日当月可免费领取10GB通用流量",
        link: "",
        remark: "需实名认证"
    },
    {
        id: 79,
        operator: "广电",
        province: "广东省",
        city: "深圳市",
        mainType: "其他活动",
        subType: ["抽奖活动"],
        title: "深圳广电用户抽奖赢iPad",
        startTime: "2026-08-15",
        endTime: "2026-08-31",
        desc: "广电用户可参与抽奖，奖品含iPad",
        link: "",
        remark: "每人每日1次"
    },
    {
        id: 80,
        operator: "广电",
        province: "全国",
        city: "全国",
        mainType: "合约购机",
        subType: ["购机补贴"],
        title: "广电全国购机补贴最高2000元",
        startTime: "2026-08-10",
        endTime: "2026-09-30",
        desc: "办理融合套餐购机补贴最高2000元",
        link: "https://www.10099.com.cn",
        remark: "限指定机型"
    }
];

// ============================================================
//  暴露给全局（供 HTML 中的活动工具箱读取）
// ============================================================
window.mainTypeEnum = mainTypeEnum;
window.subTypeMap = subTypeMap;
window.activityList = activityList;