document.write("<div id=\"new\" class=\"newHeader\">");
document.write("");
document.write("    <div class=\"topsearch\">");
document.write("");
document.write("        因为相信 所以看见");
document.write("");
document.write("    <!--    <img src=\"img\/searchNew.png\" alt=\"\" onclick=\"wapHref('http:\/\/wap.10010.com\/mobileService\/search.htm')\">-->");
document.write("");
document.write("    <\/div>");
document.write("");
document.write("<!--");
document.write("");
document.write("<marquee behavior=\"\" scrolldelay=\"100\" scrollamount=\"1\" direction=\"left\" bgcolor=\"#CCFF66\" width=\"\" height=\"20rem\">");
document.write("");
document.write("<font size=\"2\" color=\"#000\">");
document.write("");
document.write("🎤最新消息：");
document.write("");
document.write("<a href=\"#\" target=\"_blank\" style=\"color:CC6600\">新一轮竞合<\/a><\/br><\/font>");
document.write("");
document.write("<\/marquee>  -->");
document.write("");
document.write("<\/div>");
document.write("");
document.write("<div class=\"zt_body\">");
document.write("");
document.write("    <div class=\"gapTitle\" style=\"background-color:#f0f0f0;height:.2rem;\"><\/div>");
document.write("");
document.write("    <div class=\"zcl\" id=\"tab_li_div\">");
document.write("");
document.write("        <ul>");
document.write("");
document.write("            <li class=\"lb_li1 oper bj\" data-oper=\"query\" data-index=\"1\">");
document.write("");
document.write("                <p>查询<\/p>");
document.write("");
document.write("            <\/li>");
document.write("");
document.write("            <li class=\"lb_li2 oper\" data-oper=\"pay\" data-index=\"2\">");
document.write("");
document.write("                <p>手厅<\/p>");
document.write("");
document.write("            <\/li>");
document.write("");
document.write("            <li class=\"lb_li3 oper\" data-oper=\"custom\" data-index=\"3\">");
document.write("");
document.write("                <p>话费积分<\/p>");
document.write("");
document.write("            <\/li>");
document.write("");
document.write("            <li class=\"lb_li4 oper\" data-oper=\"custom\" data-index=\"4\">");
document.write("");
document.write("                <p>热门活动<\/p>");
document.write("");
document.write("            <\/li>");
document.write("");
document.write("            <li class=\"lb_li5 oper\" data-oper=\"spread\" data-index=\"5\">");
document.write("");
document.write("                <p>地区活动<\/p>");
document.write("");
document.write("            <\/li>");
document.write("");
document.write("            <li class=\"lb_li6 oper\" data-oper=\"spread\" data-index=\"6\">");
document.write("");
document.write("                <p>广东专区<\/p>");
document.write("");
document.write("            <\/li>          ");
document.write("");
document.write("           <li class=\"lb_li7 oper\" data-oper=\"spread\" data-index=\"7\">");
document.write("");
document.write("                <p>精选商城<\/p>");
document.write("");
document.write("            <\/li>                       ");
document.write("");
document.write("            <li><\/li>");
document.write("");
document.write("            <li><\/li>");
document.write("");
document.write("            <li><\/li>");
document.write("");
document.write("            <li><\/li>");
document.write("");
document.write("        <\/ul>");
document.write("");
document.write("    <\/div>");
document.write("");
document.write("<\/div>");
document.write("");
document.write("    <div class=\"t1 div_nav\">");
document.write("");
document.write("        <div class=\"t1_1\">");
document.write("");
document.write("            <ul>");
document.write("");
document.write("<!--                ");
document.write("");
document.write(" <div class=\"top1\"><a href=\"http:\/\/91haoka.cn\/webapp\/merchant\/templet1.html?share_id=386983&id=2493347\"><img width=\"290rem\" height=\"100rem\" src=\"img\/top_1.jpg\"><\/a><\/div>-->");
document.write("");
document.write(" ");
document.write("");
document.write("<p style=\"text-align: center;\">");
document.write("");
document.write("    <a id=\"obj1\"><img id=\"obj\" src=\"img\/bg01.jpg\" width=\"290rem\" height=\"130rem\" border=\"0\"\/><\/a>");
document.write("");
document.write("<\/p>                                       ");
document.write("");
document.write("                   ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/wap.10010.com\/mobileService\/clickCountLogRecord\/pageClickCount.htm?flag=new&amp;urlApp=xxx&amp;urlName=xxx&amp;application=113000010&amp;title=%e6%88%91%e5%b7%b2%e8%ae%a2%e8%b4%ad&amp;openUrl=https%3a%2f%2fm.client.10010.com%2fmobileService%2foperationservice%2fqueryOrderRelationshipTwo.htm&quot;\">                             <img src=\"img\/20161026170548.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>我已订购(旧)<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    ");
document.write("");
document.write("                   ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/wap.10010.com\/mobileService\/clickCountLogRecord\/pageClickCount.htm?flag=new&amp;urlApp=xxx&amp;urlName=xxx&amp;application=113000010&amp;title=%e4%bd%99%e9%87%8f%e6%9f%a5%e8%af%a2&amp;openUrl=https%3a%2f%2fm.client.10010.com%2fmobileService%2foperationservice%2fqueryWoComboSpare.htm&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026170637.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>余量查询(旧)<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/wap.10010.com\/mobileService\/clickCountLogRecord\/pageClickCount.htm?flag=new&urlApp=xxx&urlName=xxx&application=113000010&title=%e4%b8%9a%e5%8a%a1%e5%8a%9e%e7%90%86%e8%ae%b0%e5%bd%95&openUrl=https%3a%2f%2fm.client.10010.com%2fmobileService%2foperationservice%2fqueryHistoryBusinessBL.htm&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026171543.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>业务办理记录<\/p>");
document.write("");
document.write("                        <\/li>                    ");
document.write("");
document.write("                   ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/wap.10010.com\/mobileService\/clickCountLogRecord\/pageClickCount.htm?flag=new&urlApp=xxx&urlName=xxx&application=113000010&title=%e6%88%91%e5%b7%b2%e8%ae%a2%e8%b4%ad&openUrl=https:\/\/img.client.10010.com\/liuliangbaoliebiaov3\/index.html&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026171253.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>流量专区(旧)<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    ");
document.write("");
document.write("  					 <li name=\"https:\/\/u.10010.cn\/uAaqk\" onclick=\"window.location.href=&quot;https:\/\/img.client.10010.com\/shengyuhuafei\/index.html&quot;\"> ");
document.write("");
document.write(" 					   <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>剩余话费(旧)<\/p>");
document.write("");
document.write("                        <\/li>                  ");
document.write("");
document.write("                    ");
document.write("");
document.write("                   ");
document.write("");
document.write("                    ");
document.write("");
document.write("                   ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/wap.10010.com\/mobileService\/clickCountLogRecord\/pageClickCount.htm?flag=new&urlApp=xxx&urlName=xxx&application=113000010&title=%e4%bd%99%e9%87%8f%e6%9f%a5%e8%af%a2&openUrl=https:\/\/img.client.10010.com\/shiyongliangfenxi\/index.html&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026174033.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>使用量分析<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/img.client.10010.com\/dwguide\/index.html?title=%E8%AF%B7%E7%A8%8D%E5%90%8E&sharerMobile=&openUrl=https%3a%2f%2fimg.client.10010.com%2fwoyidinggou%2findex.html&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026170548.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>我已订购<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    ");
document.write("");
document.write("                   ");
document.write("");
document.write(" 					 <li name=\"https:\/\/u.10010.cn\/qA5AW\" onclick=\"window.location.href=&quot;https:\/\/epay.10010.com\/upp\/obppWebroot\/html\/arrearsSelect.html&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026170637.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>欠费查询<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/img.client.10010.com\/dwguide\/index.html?title=%E8%AF%B7%E7%A8%8D%E5%90%8E&sharerMobile=&openUrl=https%3a%2f%2fimg.client.10010.com%2fyewubanlijilu%2findex.html&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026171543.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>业务办理记录<\/p>");
document.write("");
document.write("                        <\/li>            ");
document.write("");
document.write(" ");
document.write("");
document.write(" 					 <li name=\"https:\/\/u.10010.cn\/qA5AW\" onclick=\"window.location.href=&quot;.\/hmd.html&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026174033.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>黑名单查询<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write(" 					 <li name=\"https:\/\/u.10010.cn\/qA5AW\" onclick=\"window.location.href=&quot;https:\/\/getsimnum.caict.ac.cn\/m\/#\/&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026171253.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>一证通查<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("  					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/spyyt.10010.com\/rcb?scene=06&chnl=04&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175413.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>视频营业厅<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    ");
document.write("");
document.write("                   ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/wap.10010.com\/mobileService\/clickCountLogRecord\/pageClickCount.htm?flag=new&urlApp=xxx&urlName=xxx&application=113000010&title=%E6%B5%81%E9%87%8F%E5%8C%85&openUrl=https:\/\/m.client.10010.com\/mobileService\/operationservice\/queryOrderRelationship.htm&title=%E4%BD%99%E9%87%8F%E6%9F%A5%E8%AF%A2&openUrl=https:\/\/wap.10010.com\/mobileService\/clickCountLogRecord\/pageClickCount.htm?flag=new&urlApp=xxx&urlName=xxx&application=113000010&title=%E6%9F%A5%E8%AF%A2&openUrl=https:\/\/m.client.10010.com\/mobileService\/operationservice\/queryOrderRelationship.htm&type=6&list_name=%E6%9C%AA%E5%91%BD%E5%90%8D&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175256.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>我的流量包<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    ");
document.write("");
document.write("                   ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/img.client.10010.com\/dwguide\/index.html?title=%E6%AD%A3%E5%9C%A8%E6%9F%A5%E8%AF%A2&sharerMobile=&openUrl=https%3A%2F%2Fm.client.10010.com%2Fmobileservicequery%2FoperationserviceNew%2FqueryOrderRelationship&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175344.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>隐藏业务(1)<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    ");
document.write("");
document.write("                   ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/img.client.10010.com\/dwguide\/index.html?title=%E6%AD%A3%E5%9C%A8%E6%9F%A5%E8%AF%A2&sharerMobile=&openUrl=https%3A%2F%2Fm.client.10010.com%2Fmobileservicequery%2Fquery%2FqueryBusinessRecordDetails&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175413.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>隐藏业务(2)<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    ");
document.write("");
document.write("                             ");
document.write("");
document.write("                ");
document.write("");
document.write("            <\/ul>");
document.write("");
document.write("        <\/div>");
document.write("");
document.write("    <\/div>");
document.write("");
document.write("    <div class=\"t2 div_nav\">");
document.write("");
document.write("        <div class=\"t1_2\">");
document.write("");
document.write("            <ul>");
document.write("");
document.write("                <!--");
document.write("");
document.write("                    	 <li name=\"\" onclick=\"window.location.href=&quot;&quot;\"> -->");
document.write("");
document.write("                       	 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/wap.10010.com\/mobileService\/operationservice\/queryOrderRelationshipTwo.htm&quot;\">                  	 ");
document.write("");
document.write("                        <img src=\"img\/20161026170548.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>我已订购<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                      	                     	                        <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/wap.10010.com\/mobileService\/operationservice\/queryWoComboSpare.htm&quot;\">               ");
document.write("");
document.write("                            <img src=\"img\/20161026170637.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>余量查询<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                        	 ");
document.write("");
document.write("                        <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/wap.10010.com\/mobileService\/operationservice\/queryHistoryBusinessBL.htm&quot;\">");
document.write("");
document.write("                            <img src=\"img\/20161026171543.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>业务办理记录<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                      <li name=\"\" onclick=\"window.location.href=&quot;http:\/\/wap.10010.com\/mobileService\/operationservice\/get_my_package.htm&quot;\">");
document.write("");
document.write("                            <img src=\"img\/b9c2a15c7dd1f37c.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>我的套餐<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    	 <li name=\"\" onclick=\"window.location.href=&quot;http:\/\/wap.10010.com\/mobileService\/common\/skip\/queryRealTimeFee.htm?navUrlCode=1160&activiChannel=wap&quot;\">");
document.write("");
document.write("                            <img src=\"img\/20161026172853.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>实时话费<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                     	 <li name=\"\" onclick=\"window.location.href=&quot;http:\/\/wap.10010.com\/mobileService\/common\/skip\/queryBalance.htm?navUrlCode=1144&activiChannel=wap&quot;\">                ");
document.write("");
document.write("                            <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>账户余额<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    ");
document.write("");
document.write("                     	 <li name=\"\" onclick=\"window.location.href=&quot;http:\/\/upay.10010.com\/npfwap\/npfMobWap\/query\/index.html?navUrlCode=1217&activiChannel=wap&quot;\">                              <img src=\"img\/20200807103824.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>交费记录<\/p>                             <\/li>");
document.write("");
document.write("                ");
document.write("");
document.write("            <\/ul>");
document.write("");
document.write("        <\/div>");
document.write("");
document.write("    <\/div>");
document.write("");
document.write("    <div class=\"t3 div_nav\">");
document.write("");
document.write("        <div class=\"t1_3\">");
document.write("");
document.write("            <ul>");
document.write("");
document.write("                ");
document.write("");
document.write("                      	 <li name=\"\" onclick=\"window.location.href=&quot;http:\/\/u.10010.cn\/qAAei&quot;\">                 ");
document.write("");
document.write("                            <img src=\"img\/20170224145740.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>交费充值<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                     	 <li name=\"\" onclick=\"window.location.href=&quot;http:\/\/wap.10010.com\/mobileService\/view\/client\/fill\/newFixCharge.jsp?navUrlCode=1090&quot;\">                               <img src=\"img\/20170224145808.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>充值卡充值<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    	 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/upay.10010.com\/npfwap\/npfMobWap\/closeAccount\/index.html?navUrlCode=1323&quot;\">                                                <img src=\"img\/20190827172359.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>销户号码交费<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                        ");
document.write("");
document.write("                        ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/img.client.10010.com\/jifenshangcheng\/goodsdetail?goodsId=8a29ac8a75a30e4e0175ba89c3dc1009&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026171253.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>积分兑换(5元)<\/p>");
document.write("");
document.write("                        <\/li>                    ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/img.client.10010.com\/jifenshangcheng\/goodsdetail?goodsId=8a29ac8a75a30e4e0175b721ae490a5a&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026171253.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>积分兑换(10元)<\/p>");
document.write("");
document.write("                        <\/li>     ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/img.client.10010.com\/jifenshangcheng\/goodsdetail?goodsId=8a29ac8a7aa5a75d017aa81f68c40131&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026171253.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>积分兑换(20元)<\/p>");
document.write("");
document.write("                        <\/li>       ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/img.client.10010.com\/jifenshangcheng\/goodsdetail?goodsId=8a29ac8a7aa5a75d017aa8254e900154&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026171253.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>积分兑换(50元)<\/p>");
document.write("");
document.write("                        <\/li>                    ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/img.client.10010.com\/jifenshangcheng\/goodsdetail?goodsId=8a29ac897aa5a75c017aa829c5ef0310&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026171253.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>积分兑换(100元)<\/p>");
document.write("");
document.write("                        <\/li>     ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/img.client.10010.com\/jifenshangcheng\/goodsdetail?goodsId=8a29ac897aa5a75c017aa827587202ed&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026171253.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>积分兑换(200元)<\/p>");
document.write("");
document.write("                        <\/li>                      ");
document.write("");
document.write("                    	 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/m.tb.cn\/h.UnuSd95&quot;\">                                                <img src=\"img\/20190827172359.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>领话费活动1<\/br>月底截止<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    	 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/3.cn\/1-C21UPJ&quot;\">     ");
document.write("");
document.write("                            <img src=\"img\/20161026172853.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>京东<\/br>积分兑换\/快充<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    	 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/atp.bol.wo.cn\/atp\/unity\/ACT20230131100038497641339qF2T?product=woemail&quot;\">                                                <img src=\"img\/20190827172359.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>每月领1元话费<\/br>月底截止<\/p>");
document.write("");
document.write("                        <\/li>                     ");
document.write("");
document.write("                        ");
document.write("");
document.write("          <!--          	 <li name=\"\" onclick=\"window.location.href=&quot;http:\/\/u.10010.cn\/0tykYLi3?channel=Face&quot;\">     ");
document.write("");
document.write("                            <img src=\"img\/20161026172853.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>年终福利<\/br>抽888红包<\/p>");
document.write("");
document.write("                        <\/li>  -->");
document.write("");
document.write("                    	 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/u.jd.com\/FMPjwJs&quot;\">      ");
document.write("");
document.write("                            <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>慢充·50话费<\/br>限时9折起<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    ");
document.write("");
document.write("                    	 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/u.jd.com\/FCD1UaK&quot;\">                        ");
document.write("");
document.write("                            <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>慢充·100话费<\/br>限时9折起<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    	 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/u.jd.com\/FMPffXS&quot;\">                         ");
document.write("");
document.write("                            <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>慢充·200话费<\/br>限时9折起<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    	 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/pay262.github.io\/tx\/img\/abc_gd.jpg&quot;\">                                                <img src=\"img\/20190827172359.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>广东农行30-5<\/br>3月31日截止<\/p>");
document.write("");
document.write("                        <\/li>          ");
document.write("");
document.write(" ");
document.write("");
document.write("                                                                        ");
document.write("");
document.write("            <\/ul>");
document.write("");
document.write("        <\/div>");
document.write("");
document.write("    <\/div>");
document.write("");
document.write("    <div class=\"t4 div_nav\">");
document.write("");
document.write("        <div class=\"t1_4\">");
document.write("");
document.write("            <ul>");
document.write("");
document.write("<!--");
document.write("");
document.write("<div class=\"top1\"><a href=\"#\"><img width=\"290rem\" height=\"100rem\" src=\"img\/bg01.jpg\"><\/a><\/div>                -->");
document.write("");
document.write("                   ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/getsimnum.caict.ac.cn\/m\/#\/&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026171253.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>一证通查<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    ");
document.write("");
document.write("  					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/img.client.10010.com\/dwguide\/index.html?title=%E6%88%91%E7%9A%84%E7%A4%BC%E5%8C%85&duanlianjieabc=&actCode=&sharerMobile=&openUrl=https%3A%2F%2Fm.client.10010.com%2FmyPrizeForActivity%2Fquerywinninglist.htm&quot;\"> ");
document.write("");
document.write(" 					   <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>我的礼包<\/p>");
document.write("");
document.write("                        <\/li>                  ");
document.write("");
document.write("                    ");
document.write("");
document.write("                                      ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/txwk.10010.com\/t\/8hzk8&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026174033.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>王卡宽带预约<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/img.client.10010.com\/5gshengjibaoduannei\/index.html?channel=5Gzhuanqu-fuwu#\/home&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/cb28db500e1f8cfa-1.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>5G升级月包<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    ");
document.write("");
document.write("                   ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;http:\/\/speed.unicomgd.com:8080\/&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026170637.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>宽带测速<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/m.tb.cn\/h.URjjrIh?tk=oQaqddlSkOv&quot;\"> ");
document.write("");
document.write("<!--\/\/5g加油包：https:\/\/c.newbuy.chinaunicom.cn\/sp\/gzclzx\/H5\/doubleEleven.html  \/\/--> 					 ");
document.write("");
document.write("                            <img src=\"img\/cb28db500e1f8cfa-1.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>5G升级日包<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write(" <!--					 <li name=\"\" onclick=\"window.location.href=&quot;http:\/\/u.10010.cn\/qAAgm&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026171543.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>福利二选一<\/p>");
document.write("");
document.write("                        <\/li>         -->   ");
document.write("");
document.write(" ");
document.write("");
document.write("                                                                        ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/m.client.10010.com\/mobileService\/businessTransact\/iceNoLimitsFlow\/iceNolimitsFlowDetail.htm&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026172853.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>畅享用流量包<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    ");
document.write("");
document.write("                   ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/img.client.10010.com\/yuyintehuibao\/index.html&quot;\"> ");
document.write("");
document.write(" 					   <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>语音特惠包<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    ");
document.write("");
document.write("                   ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/txwk.10010.com\/KCard\/wxCommon\/goto_direct?state=KCARD_CASH_INVITE_ORDER&IdType=union_id&ShareID=McpNSj29zvTpY3rcZRYy3zzdHIL5kalYvruUXKf3YzU&channel=01-0379-a5ar-a6xw&ADTAG=01-0379-a5ar-a6xw&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20200807103824.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>超值套餐<\/br><\/p>");
document.write("");
document.write("                        <\/li>   ");
document.write("");
document.write("                    ");
document.write("");
document.write("                   ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;http:\/\/u.10010.cn\/qA7K3&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175256.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>套餐升级福利<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    ");
document.write("");
document.write("                   ");
document.write("");
document.write(" 	<!--				 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/c.newbuy.chinaunicom.cn\/sp\/gzclzx\/H5\/Active5G\/ActiveFiveG.html&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175344.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>5g消息<\/p>");
document.write("");
document.write("                        <\/li>  -->");
document.write("");
document.write("                   ");
document.write("");
document.write("                   ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/huodong.10155.com\/h5\/hdact3\/spcl-ahWojoy.html#\/index?channel=3000007549&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175413.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>沃享视频会员<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                                       ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/guanjia.10010.com\/product?sgChannel=3&product=2&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175532.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>手机管家<\/br><\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/img.client.10010.com\/2023springfestival\/#\/Login?shareCode=&channel=UnicomAppN11&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175256.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>2022年度报告<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                       ");
document.write("");
document.write(" 	<!--				 <li name=\"http:\/\/u.10010.cn\/qAAgm\" onclick=\"window.location.href=&quot;https:\/\/card.10010.com\/terminal\/homepage?salesId=X2106251237463534&developerId=7610093204&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026171543.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>校园沃派套餐<\/br>阿里定向流量<\/p>");
document.write("");
document.write("                        <\/li>          -->                   ");
document.write("");
document.write("                   ");
document.write("");
document.write("<!-- 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/m.client.10010.com\/newuser_century\/view\/indexnew.jsp?encryptusernumber=3cb733d3-60ec-4b65-b141-fd07a58fa1ce&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026174033.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>新人百元礼<\/p>");
document.write("");
document.write("                        <\/li>  -->");
document.write("");
document.write("                    ");
document.write("");
document.write("                                 ");
document.write("");
document.write(" 	<!--				 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/atp.bol.wo.cn\/atp\/unity\/ACT202209281657455211276D9xbUb?product=woemail&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20181023152958.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>领1元话费<\/br>11月30日截止<\/p>");
document.write("");
document.write("                        <\/li>           -->       ");
document.write("");
document.write("                        ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/qy.chinaunicom.cn\/mobile-h5\/2023\/draw.html&quot;\"> ");
document.write("");
document.write("  					   <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                          <p>免费抽好礼<\/br><\/p>");
document.write("");
document.write("                        <\/li>       ");
document.write("");
document.write("                            ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/club.10010.com\/uf\/daily\/draw?isAuto=true&shorturl=8b40e5&quot;\"> ");
document.write("");
document.write("  					   <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                         <p>每日抽E卡<\/br><\/p>");
document.write("");
document.write("                        <\/li>       ");
document.write("");
document.write(" ");
document.write("");
document.write("  <!--					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/m.client.10010.com\/mobileService\/openPlatform\/openPlatLine.htm?to_url=https:\/\/vvm.wo116114.com:20104\/nlp\/wechat\/auth\/ecs\/login?target=gqhd&channel=st006&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20200807103824.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>抽奖·百元话费<\/p>                          <\/li>  -->");
document.write("");
document.write("                            ");
document.write("");
document.write("<!--		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/img.client.10010.com\/dwguide\/index.html?actCode=13&title=%E8%B6%85%E7%BA%A7%E5%8A%9E&openUrl=https%3A%2F%2Fu.10010.cn%2FqA7hl&duanlianjieabc=qAWhX&quot;\">   ");
document.write("");
document.write("                            <img src=\"img\/20200807103824.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>超级办<\/p>                          <\/li>         -->                  ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/qy.chinaunicom.cn\/u\/d5d126408a314272953d5a875fa8b679&quot;\"> ");
document.write("");
document.write("  					   <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>开盲盒抽会员<\/br><\/p>");
document.write("");
document.write("                        <\/li>       ");
document.write("");
document.write(" 					 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/qy.chinaunicom.cn\/u\/db7f686bc93943eb9597e74943394605&quot;\"> ");
document.write("");
document.write("  					   <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>开会员抽好礼<\/br><\/p>");
document.write("");
document.write("                        <\/li>       ");
document.write("");
document.write("                                    ");
document.write("");
document.write("            <\/ul>");
document.write("");
document.write("        <\/div>");
document.write("");
document.write("    <\/div>");
document.write("");
document.write("    <div class=\"t5 div_nav\">");
document.write("");
document.write("        <div class=\"t1_5\">");
document.write("");
document.write("            <ul>");
document.write("");
document.write("<!--            ");
document.write("");
document.write("<div class=\"top1\"><a href=\"#\"><img width=\"290rem\" height=\"100rem\" src=\"img\/bg01.jpg\"><\/a><\/div>                  -->              ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/sourl.cn\/U88mdD&quot;\">          ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>广东·专区<\/br>移步到羊毛汇<\/p>");
document.write("");
document.write("                        <\/li>      ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/wsm.wx.yn10010.com\/hall\/millionWelfare&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>云南·抽百万福利<\/p>");
document.write("");
document.write("                        <\/li>       ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;http:\/\/bjwys.bjunicom.com.cn\/apps\/shareapps\/pub-page\/updatePackage\/customInfoNew.html?shopId=01153114&qrcodeId=0130914179&goodsTypeCode=2019122500012429&y7bRbP=qAkSqarjFbNjFbNjFXsay2hNZLP8BR3Ngn5uxkfnu4ZqqEQEbG_lqAqqFG&quot;\">                                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>北京·5g升级包<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/wechat.zj186.com\/wechat-route-rest-1.0\/view\/emallCustomer\/index?developId=15657475102&quot;\">          ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>浙江·每月抽奖<\/p>");
document.write("");
document.write("                        <\/li>                       ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/wsm.wx.yn10010.com\/sms2\/lyh&quot;\">                                                                <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>云南·充值送<\/p>");
document.write("");
document.write("                        <\/li>                    ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/ahlyh.ahlt10010.com\/app\/oldUserWx\/index?number=&quot;\">                          <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>安徽·老用户专区<\/p>");
document.write("");
document.write("                        <\/li>        ");
document.write("");
document.write(" ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/u.10010.cn\/qAtZB&quot;\">                             <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>湖南·精彩活动<\/p>");
document.write("");
document.write("                        <\/li>                       ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;http:\/\/u.10010.cn\/0tyKaxuN&quot;\">                              <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>湖北·抽奖活动<\/br><\/p>");
document.write("");
document.write("                        <\/li>      ");
document.write("");
document.write("                        ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/wx.hnliantong.com\/h5\/cl\/index.html?source=2&channel_id=&openid=oZSTft3pv91FBq-eODNKRjD3FVLc&isBindMobile=0#\/product\/71&quot;\">                                                        <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>湖南·5g加油包<\/br><\/p>");
document.write("");
document.write("                        <\/li>                                 ");
document.write("");
document.write("                                                       <!--   ");
document.write("");
document.write("        		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/82612.activity-17.m.duiba.com.cn\/projectx\/pfa8c49f1\/f6a81faf1.html?appKey=3g9BRP5HuZCGg9Hk3tudXpGEF7hE&openBs=openbs&shareCode=C378W6&quot;\">                                            ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>湖南·话费券<\/p>");
document.write("");
document.write("                        <\/li>    -->                     ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/m.10010.com\/scaffold-show\/push\/74Nsm4M1Kjd?channel=06-2279-af44-aj7q&duanlianjieabc=jykdwxtw&quot;\">                                    <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>湖南·千兆宽带<\/br><\/p>");
document.write("");
document.write("                        <\/li>                       ");
document.write("");
document.write("<!--                  ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/u.10010.cn\/0tyJHGVN&quot;\">                                          ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>长沙·话费红包<\/p>");
document.write("");
document.write("                        <\/li>       ");
document.write("");
document.write("	           	 <li name=\"\" onclick=\"window.location.href=&quot;http:\/\/u.10010.cn\/0tyJ7PrO&quot;\">                        ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>福州·话费红包<\/p>");
document.write("");
document.write("                        <\/li>             -->          ");
document.write("");
document.write("                                                  <!--            		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/om.51186.com.cn\/woscancode\/sdDoubleCloud\/toFamilyVPN?key=UPaLLod7R\/yHMUaSQoYTmzMSzcs%2BsJDpYYwxNQMRFpmwsLaHpJAZ7JwdSJHStdDJBWLTO3Ki\/Zc=&quot;\">                  ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>山东·亲情网<\/br><\/p>");
document.write("");
document.write("                        <\/li>          -->                        ");
document.write("");
document.write("                                                                         		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/m.client.10010.com\/error\/busy.html&quot;\">                                                         <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>河南·200M<\/br>低消宽带<\/p>");
document.write("");
document.write("                        <\/li>      ");
document.write("");
document.write("                        ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/yxmapp.169ol.com\/wact\/webfontsbackup\/index.html?#\/index&quot;\">                              <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>四川·养熊猫<\/br>电子券京东卡<\/p>");
document.write("");
document.write("                        <\/li>        ");
document.write("");
document.write("<!--		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/m.client.10010.com\/error\/busy1.htm&quot;\">          ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>陕西<\/br>900分钟＋150g<\/p>");
document.write("");
document.write("                        <\/li>        -->               ");
document.write("");
document.write("                                                  ");
document.write("");
document.write("                        ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/m.10010.com\/scaffold-show\/subject\/18ETxw8zGxZ?duanlianjieabc=qAv9i&quot;\">           ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>河北·福利月月领<\/br><\/p>");
document.write("");
document.write("                        <\/li>         ");
document.write("");
document.write("                        ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/wxst.xsyyzx.top:8092\/flowGather\/#\/&quot;\">                                                      <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>陕西·流量集合<\/br><\/p>");
document.write("");
document.write("                        <\/li>       ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/u.10010.cn\/qAVsg&quot;\">                              <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>江西·5g优享包<\/br><\/p>");
document.write("");
document.write("                        <\/li>           ");
document.write("");
document.write("                       ");
document.write("");
document.write("            <\/ul>");
document.write("");
document.write("        <\/div>");
document.write("");
document.write("    <\/div>");
document.write("");
document.write("    ");
document.write("");
document.write("    <div class=\"t6 div_nav\">");
document.write("");
document.write("        <div class=\"t1_6\">");
document.write("");
document.write("            <ul>");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/sourl.cn\/U88mdD&quot;\">          ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>广东·专区<\/br>移步到羊毛汇<\/p>");
document.write("");
document.write("                        <\/li>      ");
document.write("");
document.write("<!--		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/apis.17wo.cn\/flowq-web\/#\/goods\/goodsOrder?productId=MTAxNjQxOA==&wealthUserId=MzUwNDE1&rebateType=2&quot;\">          ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>广东·语音包<\/br>10元130分钟<\/p>");
document.write("");
document.write("                        <\/li>      ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/apis.17wo.cn\/flowq-web\/#\/goods\/goodsOrder?productId=MTAxNjQxOQ==&wealthUserId=MzUwNDE1&rebateType=2&quot;\">                                   ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>广东·语音包<\/br>20元300分钟<\/p>");
document.write("");
document.write("                        <\/li>               ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/apis.17wo.cn\/flowq-web\/#\/goods\/goodsOrder?productId=MTAxNjE1OA%3D%3D&wealthUserId=MzUwNDE1&rebateType=2&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>广东·语音包<\/br>0元100分钟<\/p>");
document.write("");
document.write("                        <\/li>       ");
document.write("");
document.write("                        ");
document.write("");
document.write(" 		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/apis.17wo.cn\/flowq-web\/#\/goods\/goodsOrder?productId=MTAxNjIzOA==&wealthUserId=MzUwNDE1&rebateType=2&quot;\">          ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>广东·流量月包<\/br>100元30G<\/p>");
document.write("");
document.write("                        <\/li>      ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/apis.17wo.cn\/flowq-web\/#\/goods\/goodsOrder?productId=MTAxNjI0MA==&wealthUserId=MzUwNDE1&rebateType=2&quot;\">                                   ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>广东·流量月包<\/br>200元100G<\/p>");
document.write("");
document.write("                        <\/li>               ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/apis.17wo.cn\/flowq-web\/#\/goods\/goodsOrder?productId=MTAxNjI0MQ==&wealthUserId=MzUwNDE1&rebateType=2&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>广东·流量月包<\/br>300元150G<\/p>");
document.write("");
document.write("                        <\/li>                     ");
document.write("");
document.write("                        ");
document.write("");
document.write(" 		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/apis.17wo.cn\/flowq-web\/#\/goods\/goodsOrder?productId=MTAxNjE5Ng==&wealthUserId=MzUwNDE1&rebateType=2&quot;\">          ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>广东·流量季包<\/br>99元60G<\/p>");
document.write("");
document.write("                        <\/li>      ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/apis.17wo.cn\/flowq-web\/#\/goods\/goodsOrder?productId=MTAxNjE5NA==&wealthUserId=MzUwNDE1&rebateType=2&quot;\">                                   ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>广东·流量半年包<\/br>199元200G<\/p>");
document.write("");
document.write("                        <\/li>               ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/apis.17wo.cn\/flowq-web\/#\/goods\/goodsOrder?productId=MTAxNjE5NQ==&wealthUserId=MzUwNDE1&rebateType=2&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>广东·流量年包<\/br>299元360G<\/p>");
document.write("");
document.write("                        <\/li>                                            ");
document.write("");
document.write("                                                  ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/2p.17wo.cn:13021\/micropage-2b2c\/index.html#\/pages\/otherMp\/index?pageId=9021620554551591&goodsId=800000114&channelId=10110&boothCode=GD-GW23&request_timestamp=1662353523731&quot;\">                       ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>广东·承诺在网<\/br>2g或100分钟<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;gd.html&quot;\">          ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>广东·每日任务<\/br>50元京东券<\/p>");
document.write("");
document.write("                        <\/li>       ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;gd1.html&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>广东·每日任务<\/br>腾讯视频周卡<\/p>");
document.write("");
document.write("                        <\/li>       ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/apis.17wo.cn\/flowq-web\/#\/goods\/goodsOrder?productId=MTAxNjE3MQ==&wealthUserId=MzUwNDE1&rebateType=2&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>广东·流量7日包<\/br>15元10G<\/p>");
document.write("");
document.write("                        <\/li>  ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/apis.17wo.cn\/flowq-web\/#\/goods\/goodsOrder?productId=MTAxNjE5Nw==&wealthUserId=MzUwNDE1&rebateType=2&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>广东·流量月包<\/br>30元20G<\/p>");
document.write("");
document.write("                        <\/li>                          ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/apis.17wo.cn\/flowq-web\/#\/goods\/goodsOrder?productId=MTAxNjI3Mg==&wealthUserId=MzUwNDE1&rebateType=2&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>广东·5G加油包<\/br>10元5G<\/p>");
document.write("");
document.write("                        <\/li>  ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/apis.17wo.cn\/flowq-web\/#\/goods\/goodsOrder?productId=MTAxNjQxNA%3D%3D&wealthUserId=MzUwNDE1&rebateType=2&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>畅享钻石半年版<\/br>25元\/月<\/p>");
document.write("");
document.write("                        <\/li>                     ");
document.write("");
document.write("                        ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/apis.17wo.cn\/flowq-web\/#\/goods\/goodsOrder?productId=MTAxNjM5NA==&wealthUserId=MzUwNDE1&rebateType=2&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>畅享钻石会员包<\/br>25元\/月<\/p>");
document.write("");
document.write("                        <\/li>                                             ");
document.write("");
document.write(" 		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/apis.17wo.cn\/flowq-web\/#\/goods\/goodsOrder?productId=MTAxNjM5Mw==&wealthUserId=MzUwNDE1&rebateType=2&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>畅享铂金会员包<\/br>15元\/月<\/p>");
document.write("");
document.write("                        <\/li>  ");
document.write("");
document.write("     ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/apis.17wo.cn\/flowq-web\/#\/goods\/goodsOrder?productId=MTAxNjE5OQ==&wealthUserId=MzUwNDE1&rebateType=2&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/20161026175846.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>广东·畅爽美食包<\/br>20元\/月<\/p>");
document.write("");
document.write("                        <\/li>      -->                                                                                                              ");
document.write("");
document.write("            <\/ul>");
document.write("");
document.write("        <\/div>");
document.write("");
document.write("    <\/div>");
document.write("");
document.write("    <div class=\"t7 div_nav\">");
document.write("");
document.write("        <div class=\"t1_7\">");
document.write("");
document.write("            <ul>");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/u.jd.com\/FtwYN26&quot;\">                               <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>4G·CPE ￥169<\/br>全网通插卡路由<\/p>");
document.write("");
document.write("                        <\/li>      ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/u.jd.com\/FKwggIC&quot;\">                               <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>5G·CPE ￥799<\/br>插卡 WIFI5 千兆<\/p>");
document.write("");
document.write("                        <\/li>               ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/u.jd.com\/hMz8n6e&quot;\">          ");
document.write("");
document.write("                            <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>5G·CPE ￥999<\/br>插卡 WIFI6 千兆<\/p>");
document.write("");
document.write("                        <\/li>       ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/card.10010.com\/terminal\/hs?goodsId=992110122153&channel=06-0324-af29-amt4&pitChannel=06-0324-af29-amt4&quot;\">         ");
document.write("");
document.write("                            <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>5G·CPE ￥899<\/br>联通VN007+<\/p>");
document.write("");
document.write("                        <\/li>      ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;http:\/\/33.weixianghao.cn\/sai\/675784677775-153334050034243202-82883947-17787-1.htm&quot;\">                            <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>5G·CPE ￥1598<\/br>烽火 WIFI6 千兆<\/p>");
document.write("");
document.write("                        <\/li>               ");
document.write("");
document.write("	            	 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/p.pinduoduo.com\/yr76BfzI&quot;\">          ");
document.write("");
document.write("                            <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>5G·CPE ￥1559<\/br>中兴 WIFI6 千兆<\/p>");
document.write("");
document.write("                        <\/li>       ");
document.write("");
document.write(" ");
document.write("");
document.write(" 					 <li name=\"http:\/\/iqiyi.cn\/67wPVek-24\" onclick=\"window.location.href=&quot;http:\/\/iqiyi.cn\/67wPVek-24&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/iqiyi.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>爱奇艺·会员<\/br>年卡4.5折起<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                        <li name=\"http:\/\/iqiyi.cn\/f1wUN9E-01\" onclick=\"window.location.href=&quot;http:\/\/iqiyi.cn\/f1wUN9E-01&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/iqiyi.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>爱奇艺·联名会员<\/br>年卡5折起<\/p>");
document.write("");
document.write("                        <\/li>");
document.write("");
document.write("                    ");
document.write("");
document.write("  					 <li name=\"http:\/\/iqiyi.cn\/67wPVek-24\" onclick=\"window.location.href=&quot;http:\/\/iqiyi.cn\/58wVrnZ-7c&quot;\"> ");
document.write("");
document.write("                            <img src=\"img\/iqiyi.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>爱奇艺·学生会员<\/br>双11惊喜价<\/p>");
document.write("");
document.write("                        <\/li>                       ");
document.write("");
document.write("                             ");
document.write("");
document.write("		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/u.jd.com\/FLh4lgA&quot;\">          ");
document.write("");
document.write("                            <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>4G·随身WIFI<\/br>华为天际通<\/p>");
document.write("");
document.write("                        <\/li>         ");
document.write("");
document.write("                        ");
document.write("");
document.write("	       	 <li name=\"\" onclick=\"window.location.href=&quot;http:\/\/33.weixianghao.cn\/sai\/653629982576-4802034175941093544-82883947-17787-1.htm&quot;\">                    <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>5G·随身WIFI<\/br>中兴CPE WIFI6<\/p>");
document.write("");
document.write("                        <\/li>                       ");
document.write("");
document.write("          		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/u.jd.com\/5La3E4L&quot;\">                                                 <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>京东秒杀<\/br>爆品限时抢<\/p>");
document.write("");
document.write("                        <\/li>                      ");
document.write("");
document.write("          		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/card.10010.com\/terminal\/zeroBuyDetail?goodsId=992207153074&channel=06-0324-6109-axwo&quot;\">                                                 <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>高清摄像头0元<\/br>带12个月合约<\/p>");
document.write("");
document.write("                        <\/li>                     ");
document.write("");
document.write("                                                           		 <li name=\"\" onclick=\"window.location.href=&quot;https:\/\/sourl.cn\/5rQs7V&quot;\">                                                 <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>哔哩哔哩会员<\/br>1.14-1.18 ￥98<\/p>");
document.write("");
document.write("                        <\/li>                     ");
document.write("");
document.write("                                  		 <li name=\"\" onclick=\"window.location.href=&quot;&quot;\">                                                 <img src=\"img\/20161026173300.png\" onerror=\"javascript:this.src='https:\/\/img.client.10010.com\/mobileService\/view\/client\/wap\/images\/default_logo.png';\" class=\"tu1\">");
document.write("");
document.write("                            <p>指夹血氧仪19.9<\/br>先领优惠券<\/p>");
document.write("");
document.write("                        <\/li>                                                                                ");
document.write("");
document.write("            <\/ul>");
document.write("");
document.write("        <\/div>");
document.write("");
document.write("    <\/div>");